import { ifApp, NumberKeyValue, toKey } from 'karabiner.ts'

export const ifArc = ifApp('^company.thebrowser.Browser$')

export const arc = {
  addSplitView: toKey('=', '⌃⇧'),
  archiveTab: toKey('w', '⌘'),
  blankWindow: toKey('n', '⌘⌃'),
  goToSpace: (n: NumberKeyValue) => toKey(n, '⌃'),
  capture: toKey(2, '⌘⇧'),
  changeCurrentTabUrl: toKey('l', '⌘'),
  clearUnpinnedTabs: toKey('k', '⌘⇧'),
  closeWindow: toKey('w', '⌘⇧'),
  closeSplitView: toKey('-', '⌃⇧'),
  copyPageUrl: toKey('c', '⌘⇧'),
  copyUrlAsMarkdown: toKey('c', '⌘⌥⇧'),

  // https://developer.chrome.com/docs/devtools/shortcuts/
  developerTools: toKey('i', '⌘⌥'),
  developerToolConsolePanel: toKey('j', '⌘⌥'),
  developerToolElementsPanel: toKey('c', '⌘⌥'),

  enterReaderMode: toKey('r', '⌘⌥'),
  findNext: toKey('g', '⌘'),
  findPrevious: toKey('g', '⌘⇧'),
  findAndReplace: toKey('f', '⌘⌥'),
  find: toKey('f', '⌘'),
  forceRefreshThePage: toKey('r', '⌘⇧'),
  goBack: toKey('[', '⌘'),
  goForward: toKey(']', '⌘'),
  goFullScreen: toKey('f', '⌘⌃'),
  goToSidebarItem: (n: NumberKeyValue) => toKey(n, '⌘'),
  goToLastSidebarItem: toKey('9', '⌘'),
  hideArc: toKey('h', '⌘'),
  hideOtherWindows: toKey('h', '⌘⌥'),
  jumpToSelection: toKey('j', '⌘⌥'),
  minimizeWindow: toKey('m', '⌘'),
  newEasel: toKey('e', '⌃⇧'),
  newIncognitoWindow: toKey('n', '⌘⇧'),
  newLittleArcWindow: toKey('n', '⌘⌥'),
  newNode: toKey('n', '⌃'),
  newNodeInSplit: toKey('n', '⌥⌃'),
  newTab: toKey('t', '⌘'),
  newWindow: toKey('n', '⌘'),
  nextSpace: toKey('→', '⌘⌥'),
  nextTab: toKey('↓', '⌘⌥'),
  openCommandBar: toKey('l', '⌘'),
  openExtensions: toKey('e', '⌘'),
  openLittleArcTabIn: toKey('o', '⌘'),
  pasteAndMatchStyle: toKey('v', '⌘⌥⇧'),
  pinTab: toKey('d', '⌘'),
  preferences: toKey(',', '⌘'),
  previousSpace: toKey('←', '⌘⌥'),
  previousTab: toKey('↑', '⌘⌥'),
  print: toKey('p', '⌘'),
  quitArc: toKey('q', '⌘'),
  refreshThePage: toKey('r', '⌘'),
  reopenLastClosedTab: toKey('t', '⌘⇧'),
  revealCurrentTab: toKey('␣', '⌃'),
  revealHideSidebar: toKey('s', '⌘'),
  savePageAs: toKey('s', '⌘⇧'),
  showLittleArcOpenInMenu: toKey('o', '⌘⇧'),
  stopLoading: toKey('.', '⌘'),
  switchToSplitView: (n: 1 | 2 | 3 | 4) => toKey(n, '⌃⇧'),
  switchToNextSplitView: toKey(']', '⌃⇧'),
  switchToPreviousSplitView: toKey('[', '⌃⇧'),
  tabSwitcherBackward: toKey('⇥', '⌃⇧'),
  tabSwitcherForward: toKey('⇥', '⌃'),
  viewDownload: toKey('j', '⌘⇧'),
  viewHistory: toKey('y', '⌘'),
  viewLibrary: toKey('l', '⌘⇧'),
  viewSource: toKey('u', '⌘⌥'),
  zoomIn: toKey('=', '⌘'),
  zoomOut: toKey('-', '⌘'),
  zoomToActualSize: toKey(0, '⌘'),
}
